version: "3.7"
services:
  db-migration:
    #build: .
    image: erikbra/grate:latest
    environment:
      # don't configure passwords here for real.  This is just a sample!
      APP_CONNSTRING: "Server=your-remote-public-ip-address:your-remote-port;Database=your-db;User Id=your-user-id;Password=your-user-pass;TrustServerCertificate=True"
      VERSION: "1.0.0.0"
      DATABASE_TYPE: "postgresql" # sqlite, oracle, postgresql, sqlserver, mariadb
    volumes:
      - ./db:/db
      - ./output:/output

#  PT: In this demo the PostgreSQL DB Server is bare-metal installed on a Debian 12 Linux PC connected to a Router that port-forwards to it.
#  PT: Ergo, the Docker container is not needed.
#    depends_on:
#      - db
#  db:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    environment: 
#      - SA_PASSWORD=gs8j4AS7h87jHg # again, plain text passwords are bad mmkay!
#      - ACCEPT_EULA=Y
#      - MSSQL_PID=Express
#    ports:
#      - "1433:1433"
